### PR TITLE
Less lazy code

### PR DESCRIPTION
**Pull request by Real-Packet**
less slop?!?!?!?

### CODE REVIEW

**Comment by 7GrandDadPGN** [comment]
1e3 🪦, also lazy code is my pride, you aren't taking that away from me 😠

**Comment by Real-Packet** [comment]
> 1e3 🪦, also lazy code is my pride, you aren't taking that away from me 😠

Ok lol

**Review by 7GrandDadPGN — COMMENTED** [review]
remove bad space formatting 🤮

**Comment by Real-Packet** [comment]
removed the space between the `function` keyword and `(` inserted by the crappy formatter

**Pull request merged**
